### ISSUE TITLE
Illegal division by zero at /My-path-to-RELEASE-1.5.5/ROUGE-1.5.5.pl line 2450.

### ISSUE THREAD

**Issue by IreneZihuiLi** [andersjo/pyrouge#5]
2017-11-30 21:18:25,950 [MainThread  ] [INFO ]  Written ROUGE configuration to /tmp/tmp830awd6_/rouge_conf.xml
2017-11-30 21:18:25,950 [MainThread  ] [INFO ]  Running ROUGE with command /home/lily/zl379/Projects/pointer-generator-rouge/RELEASE-1.5.5/ROUGE-1.5.5.pl -e /home/lily/zl379/Projects/pointer-generator-rouge/RELEASE-1.5.5/data -c 95 -2 -1 -U -r 1000 -n 4 -w 1.2 -a -m /tmp/tmp830awd6_/rouge_conf.xml
**Illegal division by zero** at /home/lily/zl379/Projects/pointer-generator-rouge/RELEASE-1.5.5/ROUGE-1.5.5.pl line 2450.
Traceback (most recent call last):
  File "rouge_baseline2.py", line 20, in <module>
    output = r.convert_and_evaluate()
  File "/data/tools/tf1/lib/python3.5/site-packages/pyrouge-0.1.3-py3.5.egg/pyrouge/Rouge155.py", line 364, in convert_and_evaluate
    rouge_output = self.evaluate(system_id, rouge_args)
  File "/data/tools/tf1/lib/python3.5/site-packages/pyrouge-0.1.3-py3.5.egg/pyrouge/Rouge155.py", line 339, in evaluate
    rouge_output = check_output(command).decode("UTF-8")
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/lily/zl379/Projects/pointer-generator-rouge/RELEASE-1.5.5/ROUGE-1.5.5.pl', '-e', '/home/lily/zl379/Projects/pointer-generator-rouge/RELEASE-1.5.5/data', '-c', '95', '-2', '-1', '-U', '-r', '1000', '-n', '4', '-w', '1.2', '-a', '-m', '/tmp/tmp830awd6_/rouge_conf.xml']' returned non-zero exit status 255

**Comment by Opdoop** [comment]
Hi, @IreneZihuiLi I met the same error. Have you solve the problem?

**Comment by Opdoop** [comment]
Seems that the pyrouge is incompatible with Chinese or other non-english languages.
